### ISSUE TITLE
Question/Bug: Too late formatting and long update time

### ISSUE THREAD

**Issue by Chaitanyabsprip** [jose-elias-alvarez/null-ls.nvim#1]
does the null-ls server update only depending on the debounce period or other triggers too?
I have noticed that when I edit and save my file it doesn't format it on the first save, neither the second if its too fast. It takes some time and then formats the file. I am trying to move to null-ls.nvim from efm.

**Comment by jose-elias-alvarez** [comment]
The debounce period actually only affects diagnostics (another reason why I need to get around to writing documentation). null-ls will spawn the formatter subprocess when `vim.lsp.buf.formatting` is called and attempt to apply the edits to the current buffer once it's done, but it won't apply edits if the current buffer is modified, so I wonder if that's related. 

Could you tell me which formatter you're using and what your save on format config looks like? If you could provide a sample file that consistently produces problems, that would be super helpful, too.

**Comment by Chaitanyabsprip** [comment]
This is my null-ls config
```lua
local null_ls = require "null-ls"

null_ls.setup {
    save_after_formatting = true,
    sources = {
        null_ls.builtins.formatting.lua_format,
        null_ls.builtins.formatting.prettier.with({
            filetypes = {"css", "html", "json", "sass", "yaml"}
        })
    },
    filetypes = {"css", "html", "json", "sass", "yaml"}
}
```

This is my format on save autocmd
```viml
augroup auto_format
  autocmd!
  autocmd BufWritePre * lua vim.lsp.buf.formatting_sync(nil, 1000)
augroup end
```

**Comment by jose-elias-alvarez** [comment]
Could you try changing your autocmd to:

```vim
autocmd BufWritePost * lua vim.lsp.buf.formatting()
```

And see if that makes a difference? null-ls formatting is, essentially, always asynchronous, but `save_after_format` will make it so that it saves the file after formatting completes.

Also, if you haven't, could you try updating to the latest version of the plugin? 

I'll also mention that Prettier and lua-format are both pretty slow on large files, which can make asynchronous formatting feel a bit strange. I recently added built-ins for [prettierd](https://github.com/fsouza/prettierd), which is more or less a faster drop-in replacement for Prettier, and [StyLua](https://github.com/JohnnyMorganz/StyLua), another Lua formatter that's more opinionated than lua-format but is quite a bit faster. I'd recommend using those if it's at all a possibility for you.

**Comment by Chaitanyabsprip** [comment]
I have been using these formatters with efm and they've been working fine. 
For some reason, now the setup of null-ls is not working, it isn't attaching to buffer. I'll debug it a bit more later and let you know whatever I find out. if at all anything

**Comment by jose-elias-alvarez** [comment]
Interesting, that's an issue I haven't seen. For example, after opening a Lua file, you're not seeing null-ls in the list of clients attached to the buffer when you run `:LspInfo`? Does the same thing happen both for Lua files and for the Prettier filetypes you've defined? 

Let me know if you find anything out and if you need any help debugging. If attaching is the issue, I can add some simple debug logs to the attach methods to see what's going on.

**Comment by jose-elias-alvarez** [comment]
FYI, I pushed a small change that should help with potential attach issues. If you could try updating and seeing if the issues persist, that would be great.

**Comment by jose-elias-alvarez** [comment]
Going to close this for now, but feel free to open up another issue if you're still using the plugin and run into issues.
