### ISSUE TITLE
on-demand `params` generator argument creation and deepcopying

### ISSUE THREAD

**Issue by haolian9** [jose-elias-alvarez/null-ls.nvim#1048]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

currently, each `params` passed to generator contains a `content` key which might hold huge bytes of data; even worse, the params will be deepcopied for each generator and each completion.

in my use, i rarely use the whole lines of current buffer, the cursor/current line is what i want all the time; and i never modify the `params`, so deepcopying it is unnecessary.

(i have scratched a [commit](https://github.com/haolian9/null-ls.nvim/commit/8affe88ee2f716024eb6a85c4c8d80773a3e876f) which added an option `copy_params: bool` for generator and `with_content: bool` for util.make_params, maybe that can explain my need better.)

### Help

No

**Comment by jose-elias-alvarez** [comment]
Your implementation seems pretty reasonable, and I think this is worth looking into if we can profile and determine that it's worth the added complexity. A couple of questions:

1. How would we choose which methods should have `with_content = true`? Completion and hover seem like good candidates, since those results are based on the cursor position. We'd want to make sure to document this, too.
2. I added deep copying because I found that it was too easy for sources to leak and modify the same object, which caused unpredictable behavior. What do you think of changing the logic so that we only copy if more than one generator is using the same object?

**Comment by haolian9** [comment]
sorry for the delay!
(i was also waiting if there are otheres interest in this, seems no one. because no new comments were appended.)

for 1)
 i'm still not clear on this, `with_content` or whatever name in my use is a hard code,
it should be configurable, but i was too lazy to make it that way in that time.
i personally only use diagnositc, completion parts of null-ls.nvim, they works fine with `nvim_get_current_line`, but i had met an error when it's called in formatter part.

for 2)
it's a trade off IMO. as an user, i clearly know what i'll do to the params, so i dont need this costly safety guard; but for users does not care about this, this guard is worth.
and that' s why i made the options i had added work like as default (adding content, deep copying, unless i set them to false explicitly).

**Comment by jose-elias-alvarez** [comment]
Well, without data showing that this is actually a problem, I'm not sure whether it's worth moving forward with this. Making this configurable would basically break every built-in source we have here, so even if there is a performance issue, I'd want to think carefully about how to proceed. Performance-wise, I think avoiding deep copying unless multiple sources are active will make a difference.

**Comment by haolian9** [comment]
agree.
