### ISSUE TITLE
Set `vim.diagnostic` per server

### ISSUE THREAD

**Issue by mikatpt** [jose-elias-alvarez/null-ls.nvim#1094]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Small feature request.

In standard LSP setups, you may set custom LSP handlers as so:
```lua
local format_handlers = {
    ['textDocument/publishDiagnostics'] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
        underline = true,
        virtual_text = false,
        signs = true,
        update_in_insert = false,
        severity_sort = true,
    }),
    ['window/showMessageRequest'] = function(_, result)
        return result
    end,
}

require('lspconfig').server_name.setup({ handlers = format_handlers })
```

Browsing previous issues (https://github.com/jose-elias-alvarez/null-ls.nvim/issues/525), it seems like null-ls uses the new `vim.diagnostic` API. We can replicate the above behavior for null-ls via namespaces (shown below), but I'd love a way to configure diagnostic display on a per-server basis. (I frequently turn off virtual text for noisy linters).

Supporting `handlers` in the `.with({})` config for sources seems like it might be a simple fix?

Alternatively, if this capability already exists, would love for someone to point me to the way.

Thanks!

```lua
local namespaces = vim.diagnostic.get_namespaces()
for id, tbl in pairs(namespaces) do
    local name = string.lower(tbl.name)
    local idx = string.find(name, 'null')
    if idx ~= nil then
        vim.diagnostic.config({
            underline = true,
            virtual_text = false,
            signs = true,
            update_in_insert = false,
            severity_sort = true,
        }, id)
    end
end
```

### Help

No

**Comment by jose-elias-alvarez** [comment]
So you're saying you want all null-ls diagnostics sources to use a single namespace? That will break any diagnostics sources that simultaneously publish diagnostics for multiple files, unfortunately (which is why the change was made in the first place) so we cannot change how this works by default. I guess we could add a way for users to configure how namespaces are generated (say, via a callback) but I'm not sure if there are any use cases beyond this one. Your workaround seems like a pretty good solution to me.

**Comment by mikatpt** [comment]
Hm, not necessarily - as an example, if I only wanted to turn off virtual text for `eslint`, but not other servers, how would I do this? The old `lspconfig` way would be to set customer handlers for that server.

i.e. something like 
```lua
null_ls.builtins.diagnostics.eslint.with({
    handlers = format_handlers,
}),
```

Individual namespaces (i.e. `NULL_LS_ESLINT`) would work too, since you'd be able to match on it via the `get_namespaces` workaround.

Totally fine if it's more trouble than it's worth - this is a pretty minor ask for the most part.

**Comment by jose-elias-alvarez** [comment]
I think I'm confused by how you're using the term "server," which I understand to mean all of null-ls (versus an individual source, e.g. ESLint). At the moment, [each source uses its own namespace](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/cdef04dfad2d1a6d76f596ac63600e7430baaabe/lua/null-ls/diagnostics.lua#L11), though the way names are generated is opaque (deliberately, since the goal is to avoid collisions). The following workaround should work, though it's nasty and relies on internal methods:

```lua
local null_ls = require("null-ls")

-- replace with whatever linter you are interested in
local markdownlint = null_ls.get_source({ name = "markdownlint", method = null_ls.methods.DIAGNOSTICS })[1]
if markdownlint then
    local namespace = require("null-ls.diagnostics").get_namespace(markdownlint.id)
    vim.diagnostic.config({
        underline = true,
        virtual_text = true,
        signs = true,
        update_in_insert = false,
        severity_sort = true,
    }, namespace)
end
```

It's possible for us to allow users to configure how names are generated or use source names instead of IDs, but there's no guarantee of uniqueness, so I suspect this will cause hard-to-debug issues. Still, I think your request is reasonable, so I will look into how we can make this configurable.

**Comment by mikatpt** [comment]
Oops, I definitely meant source. Terminology is hard. 

Yep this is what I was asking for, I wasn't sure how to target the specific source namespaces. Thanks a bunch!

For what it's worth, I think the most intuitive solution for me would be something resembling the following:
```lua
null_ls.builtins.diagnostics.eslint.with({
  diagnostic_config = { --[[ vim.diagnostic config options --]] },
})
```
...and then internally run `vim.diagnostic.config(diagnostic_config, namespace)`.

**Comment by jose-elias-alvarez** [comment]
Agreed, I like your proposed solution. Putting up a PR shortly!
