### ISSUE TITLE
[null-ls] failed to run generator: ...site\pack\packer\start\null-ls.nvim/lua/null-ls/loop.lua:165: command eslint_d is not executable (make sure it's installed and on your $PATH)

### ISSUE THREAD

**Issue by kul-sudo** [jose-elias-alvarez/null-ls.nvim#1118]
Nvim version: `v0.8.0-dev-1112-g6d557e324 #1118`

`[null-ls] failed to run generator: ...site\pack\packer\start\null-ls.nvim/lua/null-ls/loop.lua:165: command eslint_d is not executable (make sure it's installed and on your $PATH)`

Every single time I go into a .jsx file of my NextJS project, I see this message. The linter does not work indeed.
I use the well-known Devaslife's config: https://github.com/craftzdog/dotfiles-public

![image](https://user-images.githubusercontent.com/95244851/190913526-babc9537-f1fc-4fe2-ae9a-c9b04083213a.png)

`eslint_d` is in my environment variables: 
![image](https://user-images.githubusercontent.com/95244851/190913692-37f4d1c2-2265-43d6-821a-8c52339ab5dd.png)

**Comment by jose-elias-alvarez** [comment]
Please do not delete the issue template - without that information there is nothing I can do about this.

**Comment by kul-sudo** [comment]
C:\Users\User\AppData\Roaming\npm\eslint_d

**Comment by kul-sudo** [comment]
> Please do not delete the issue template - without that information there is nothing I can do about this. In addition to that, what does Neovim output when you run `:echo exepath("eslint_d")`?

C:\Users\User\AppData\Roaming\npm\eslint_d

**Comment by YangShaoyue** [comment]
Hi, I just encountered this issue and solved it with `:MasonInstall eslint_d`.

Yesterday, I installed eslint with `npm i eslint -g` and everything was OK, it linted well in my frontend project, but today when I reopened that project, eslint is not working.
I changed eslint to eslint_d and installed it with npm as well `npm i -g eslint_d`, but it had the same issue too. Until I installed eslint_d using `Mason` in Neovim.

It's very weird still, eslint and eslint_d both are executable globally in PowerShell, and in Neovim the output of `:echo exepath("eslint_d")` is `C:\Users\ysy\AppData\Roaming\npm\eslint_d`, seems everything is OK.

Maybe it is `null-ls`'s bug? @jose-elias-alvarez 

## Platform Info
System: Windows 11
Neovim version:
![图片](https://user-images.githubusercontent.com/12428824/211456136-3119ef17-cc2d-44ba-883c-402dd4948cdd.png)

**Comment by jose-elias-alvarez** [comment]
If it is a bug, then it's a bug with the mechanism we use to spawn processes, in which case there's very little we can do about it. I believe this is somehow related to Node executables on Windows, but learning more will require deep investigation, and I don't have a Windows development environment to test this out for myself (and it also seems to be working without problems for most users).

**Comment by YangShaoyue** [comment]
I think I find the reason, maybe null-ls can choose linter executable path according to system platform? I'm not familiar with Lua, it's just a guess.

Here is my investigation:
A few hours ago, I installed stylelint using `npm i --save-dev stylelint` (and also `npm i -g stylelint`)  for my frontend project, when I opened a .scss file, the same problem came out, just like this eslint issue.
```
[WARN  2023/1/11 21:00:28] ...ack\packer\start\null-ls.nvim/lua/null-ls/generators.lua:94: failed to run generator: ...site\pack\packer\start\null-ls.nvim/lua/null-ls/loop.lua:154: F:\Workspace\medical-insurance\node_modules\.bin\stylelint
[TRACE 2023/1/11 21:04:12] ...te\pack\packer\start\null-ls.nvim/lua/null-ls/client.lua:97: starting null-ls client
[TRACE 2023/1/11 21:04:12] ...\site\pack\packer\start\null-ls.nvim/lua/null-ls/rpc.lua:102: received LSP request for method initialize
[TRACE 2023/1/11 21:04:12] ...\site\pack\packer\start\null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method initialized
[TRACE 2023/1/11 21:04:12] ...\site\pack\packer\start\null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method textDocument/didOpen
[TRACE 2023/1/11 21:04:12] ...ack\packer\start\null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG 2023/1/11 21:04:12] ...t\null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:320: spawning command "F:\\Workspace\\medical-insurance\\node_modules\\.bin\\stylelint" at F:\Workspace\medical-insurance with args { "--formatter", "json", "--stdin-filename", "F:\\Workspace\\medical-insurance\\packages\\renderer\\report.scss" }
[WARN  2023/1/11 21:04:12] ...ack\packer\start\null-ls.nvim/lua/null-ls/generators.lua:94: failed to run generator: ...site\pack\packer\start\null-ls.nvim/lua/null-ls/loop.lua:165: command F:\Workspace\medical-insurance\node_modules\.bin\stylelint is not executable (make sure it's installed and on your $PATH)
```

In `F:\Workspace\medical-insurance\node_modules\.bin`, there are 3 executable stylelint files:
 - stylelint (which is a `sh` script actually)
![图片](https://user-images.githubusercontent.com/12428824/211824243-596439a9-3c1d-4375-9a2a-1c9214102f18.png)
- stylelint.cmd (this file content is omitted because it is not important for current issue)
- stylelint.ps1 (this file content is omitted because it is not important for current issue)

Obviously in Windows platform sh script cannot be executed directly (the other two scripts `.cmd` and `.ps1` can be executed directly), so null-ls fails to execute linter in this situation. When I delete `F:\Workspace\medical-insurance\node_modules\.bin\stylelint`, the problem is gone.

I checked out corresponding files according to trace stack, maybe `dynamic_command` function is relevant to this issue? but I'm totally new to Lua and not able to go deeper so far.

Hope this helps.

**Comment by jose-elias-alvarez** [comment]
Definitely helpful, thanks for looking into this. I had thought that `exepath()` took care of this on Windows - we use it [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/915558963709ea17c5aa246ca1c9786bfee6ddb4/lua/null-ls/loop.lua#L147), and [this nvim-lspconfig issue](https://github.com/neovim/nvim-lspconfig/issues/2130) seems to indicate that that's the right solution. What is the output from this command? 

```vim
:exepath("F:\Workspace\medical-insurance\node_modules\.bin\stylelint")
```

**Comment by YangShaoyue** [comment]
> I often switch programming computer between my  personal computer and working computer, the frontend project path and Node.js path are not identical. So I want to use `[..]` to represent different path in case of  various paths make you confusing. Those two computers both are in Windows 11 platform.
> - [NPM_PATH] means NPM installation path
> - [PROJECT_PATH] means frontend project path
> - [~] means Windows system local path which is `C:\Users\[username]`

Is there `:exepath(......)` command in Neovim? I think you mean `:echo exepath(......)`.
Maybe `eslint_d` could expose more debugging info because it can be installed with NPM (globally and locally) and Mason, I can not find `eslint` and `stylelint` in Mason Linter. Here are various outputs in different situations:

## Situation 1
- [x] installed as project devDependency `npm i --save-dev eslint_d`
- [ ] installed globally `npm i -g eslint_d`
- [ ] installed with Mason `:MasonInstall eslint_d`
`:echo exepath("eslint_d")` outputs nothing
`:echo exepath("[PROJECT_PATH]\node_modules\.bin\eslint_d")` outputs nothing

In this situation, this issue comes out when I open a `.js` or `.jsx` file.

## Situation 2
- [x] installed as project devDependency `npm i --save-dev eslint_d`
- [x] installed globally `npm i -g eslint_d`
- [ ] installed with Mason `:MasonInstall eslint_d`
`:echo exepath("eslint_d")` outputs `[NPM_PATH]\eslint_d`
`:echo exepath("[NPM_PATH]\eslint_d")` outputs nothing
`:echo exepath("[PROJECT_PATH]\node_modules\.bin\eslint_d")` outputs nothing

In this situation, this issue comes out too when I open a `.js` or `.jsx` file

## Situation 3
- [x] installed as project devDependency `npm i --save-dev eslint_d`
- [x] installed globally `npm i -g eslint_d`
- [x] installed with Mason `:MasonInstall eslint_d`
`:echo exepath("eslint_d")` outputs `[~]\AppData\Local\nvim-data\mason\bin\eslint_d.CMD`
`:echo exepath("[~]\AppData\Local\nvim-data\mason\bin\eslint_d.CMD")` outputs nothing

In this situation, this issue disappeares when I open a `.js` or `.jsx` file, eslint_d runs well.

## Situation 4
But, after Situation 3, in Neovim Mason when I uninstall eslint_d, eslint runs well still in frontend project, the output is the same as Situation 3, until I delete `[~]\AppData\Local\nvim-data\mason\bin\eslint_d.CMD` manually (this file is still there even though eslint_d is uninstalled).
Then I reinstalled eslint_d in Neovim Mason, the weird thing came out, eslint_d was not working yet. I checked related files in `...\nvim-data\mason` and seemed that eveny file was exactly the same as Situation 3.

 Maybe there are some other reasons and I'm working on solving the problem in Situation 4.

**Comment by YangShaoyue** [comment]
Yes, this patch solved current issue.

And this line
```
resolved_command = u.path.join(resolved_command, ".cmd")
```
should actually be
```
resolved_command = resolved_command .. ".cmd"
```
or `resolved_command ` value will be  `...\node_modules\.bin\eslint\.cmd`.

In addition, under this patch, `:echo exepath("eslint")` outputs nothing

**Comment by jose-elias-alvarez** [comment]
Ah, yeah, my bad. Is there any documentation about how `npm` creates these scripts in `node_modules/.bin`? If this is the documented Windows behavior, then I think the solution in the patch is fine.

**Comment by YangShaoyue** [comment]
I've been looking for that documentation after I tried this patch. I'm not very familiar with npm executable script creation mechanism. I will let you know if I find it.

**Comment by IronLu233** [comment]
Hi, @jose-elias-alvarez I found how does npm determine the executable file.

https://github.com/npm/libnpmexec/blob/e1378fc8b8e2243765b068d8eb45aba7d01d45bd/lib/index.js#L38

```js
const exec = async (opts) => {
  const {
    args = [],
    call = '',
    color = false,
    localBin = resolve('./node_modules/.bin'),
    locationMsg = undefined,
    globalBin = '',
    output,
    packages: _packages = [],
    path = '.',
    runPath = '.',
    scriptShell = isWindows ? process.env.ComSpec || 'cmd' : 'sh',
    yes = undefined,
    ...flatOptions
  } = opts
```

So the patch is correct. I create a new PR for it. #1341
