### ISSUE TITLE
`eslint` support on monorepo project

### ISSUE THREAD

**Issue by nuanyang233** [jose-elias-alvarez/null-ls.nvim#1181]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

My project is: [Maskbook](https://github.com/DimensionDev/Maskbook), the project structure uses `monorepo`, and there are multiple packages and package.json inside packages. The `eslint` configuration of null-ls built-in is based on `package.json` to match. And it doesn't match tsconfig.eslint.json, which causes an error, I tried to change it but it only eliminates the error but `eslint` doesn't work.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/28348152/194924534-5cf43d0f-ad92-4619-aa5b-a8396d0a3674.png">

This is my custom configuration, I'm not an expert in neovim, but I'm guessing this is a problem with the built-in support for null-ls? So I created a feature request and not an issue.

```
{
    command = "eslint",
    filetypes = { "javascript", "typescript", "typescriptreact", "javascriiptreact" },
    args = { "-f", "json", "--stdin", "--stdin-filename", "$FILENAME" },
    cwd = h.cache.by_bufnr(function(params)
      return u.root_pattern(
        "tsconfig.eslint.json",
        -- https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new
        "eslint.config.js",
        -- https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-file-formats
        ".eslintrc",
        ".eslintrc.js",
        ".eslintrc.cjs",
        ".eslintrc.yaml",
        ".eslintrc.yml"
      )(params.bufname)
    end),
    prefer_local = "node_modules/.bin",
  },

```

### Help

No

**Comment by jose-elias-alvarez** [comment]
I'm not sure I understand what you're trying to do. I see that your project has a `tsconfig.eslint.json` file, but this is not ann ESLint config file. It looks like your actual config file is `packages/.eslintrc.json`, which [null-ls already picks up](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/4342844954e89bca0e93a8057538000b7a9b737d/lua/null-ls/builtins/diagnostics/eslint.lua#L56).

The issue is pretty clear: when you edit a file in `packages`, null-ls will traverse the file system upwards to find the first matching ESLint config file, which is `packages/.eslintrc.json`. That config file points at `./tsconfig.eslint.json`, but that file doesn't actually exist (it's at the top level) so ESLint shows the error you are seeing.

This is fundamentally an issue with a project structrue and not something null-ls should work around. I don't know why you have two separate ESLint config files (one at the top level and one in `packages` but you should either have one config file per package or one top-level config. (You could also change the path to `../tsconfig.eslint.json` but that may cause issues for other integrations like the VS Code plugin.)
