### ISSUE TITLE
Add a method to find builtins with server name.

### ISSUE THREAD

**Issue by DoeringChristian** [jose-elias-alvarez/null-ls.nvim#1190]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Hi,

I am using Mason to install null-ls servers with the plugin [mason-null-ls.nvim](https://github.com/jayp0521/mason-null-ls.nvim).
This plugin gives me a string with the name of the installed server. I would like to automatically enable all builtins for that server. When testing if there exists a formatter, code_action etc using:
```lua
if null_ls.builtins.formatting[source_name] ~= nil then
    null_ls.register(null_ls.builtins.formatting[source_name])
end
```
I get a warning if the server does not support formatting.
Is there a way to test if this builtin does exist?
If not could this be implemented?

Thanks for your Help.

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
Sorry, I'm not sure I understand the request. Don't the source names from mason-null-ls match the source names here?

**Comment by jose-elias-alvarez** [comment]
Right, so if the names match, then what is the issue? At what point do you access a built-in that doesn't exist?

The existing warning is important to prevent issues caused by typos, and I'd be hesitant to add a method for such a specific use case.

**Comment by DoeringChristian** [comment]
The problem is that I don't know if the source supports formatting, code_actions etc. I would need to test if the source is in builtin.formatting, builtin.code_action etc.
[example](https://github.com/DoeringChristian/nvim-config/blob/c9a51f572fcf014eec5cebd601f13a514091477d/lua/user/mason.lua#L78).

**Comment by jose-elias-alvarez** [comment]
I see. This is something we could add here, but I think a better solution might be to have mason-null-ls pass more information than just the source's name to user-defined handlers. As you've seen, the name alone is not enough context to properly handle the source, especially since sources like ESLint have the same name but 3 different methods.

**Comment by jose-elias-alvarez** [comment]
I think there's some confusion about terminology here because I'm not sure what you mean by "source" (maybe Mason has its own definition?). If I understand correctly, you want to know if a given command (e.g. `eslint`) is supported by null-ls, and if so, you want to know which methods it supports. Is that right?

If so, it's a pretty niche use case, but it's not something that's easy to do right now, so I think we can support it. The best approach would probably be to add it to our generated metadata so that you could do something like this:

```lua
local command_map = require("null-ls.builtins._meta.command_map") -- doesn't exist yet!
local commands = { "eslint", "prettier" } -- these are the commands we want to check

for _, command in ipairs(commands) do
    local methods = command_map[command]
    if methods then
        for _, method in ipairs(methods) do
            null_ls.register(null_ls.builtins[method][command])
        end
    end
end
```

If this seems like a good solution, I can put something together.
