### ISSUE TITLE
Improve documentation around BUILTINS #81

### ISSUE THREAD

**Issue by euoia** [jose-elias-alvarez/null-ls.nvim#124]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I tried the most minimal example and then attempted to format a .lua file.

Here's my Packer config:

	-- null-ls bridges the gap between command-line tools and language server.
	-- Adds support for, for example, eslint, prettier, etc.
	use({
		"jose-elias-alvarez/null-ls.nvim",
		requires = { { "neovim/nvim-lspconfig" }, { "nvim-lua/plenary.nvim" } },
		config = function()
			require("null-ls").config({
				sources = { require("null-ls").builtins.formatting.stylua },
			})
			require("lspconfig")["null-ls"].setup({})
		end,
	})
But when I ran :lua vim.lsp.buf.formatting() was presented with the error:

null-ls: failed to run generator: ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:115: command: expected string (executable), got stylua
After installing stylua the error went away and I was able to format lua files.

Here are some suggestions:

Consider stating closer to the top of the main README that builtins must installed on the system. Even better, state how they are resolved (does it resolve using the PATH environment variable?).
Modify the BUILTINS.md document to state that the executables must be installed on the system.
Consider changing the name BUILTINS to something else, maybe OUT-OF-THE-BOX or SUPPORTED-TOOLS or sonething.
Consider changing the error message, and perhaps differentiating between type(v) == "string" and vim.fn.executable(command) > 0? For example, it might be helpful to state command was either not a string, or command was not executable (and to refer to the documentation).
Consider that (in my opinion anyway) the majority of users will be looking to simply use one of the builtins, as opposed to writing their own sources. It might be worth clarifying the distinction better in the main README.
Just for my own curiosity, if the builtins rely on locally provided executables, how does the source specify which version of the tool it is compatible with? Or is that down to the source? For example, what happens if my local version of an executable is missing a feature that is relied up by the source? I think it would be helpful to have this information in either README.md or BUILTINS.md.

I think this is related to #118.

Thanks for this plugin, by the way. I really like the approach.

### Help

Yes

### Implementation help

I would happily submit a pull request to improve the documentation, but am somewhat cautious about modifying the top level documentation for someone else's project. Happy to help if I can.

**Comment by jose-elias-alvarez** [comment]
I agree that we could improve the documentation and would review / merge a PR when I have time (I won't have enough time to work on it myself for a while, since I'm dealing with illness followed by an international move). I'm not likely to change the name at this point because I think it's a lot of effort and I'd rather just clarify that you need the given command installed. I do definitely want to improve the error message, since it was mentioned in another issue too. 

To briefly answer your questions and hopefully provide a temporary resource for anybody else searching:

1. Executables are resolved in the same way Neovim itself resolves executables, which usually lines up with `$PATH`. Given a command, e.g. `cat`, if `:echo executable("cat")` shows `1` and `!cat` works from Neovim, the executable will resolve correctly. 
2. The command will run exactly as if you had run it yourself from the command line, so I don't think version incompatibilities are something users need to worry about. As far as I know we don't have any version-dependent sources, but it would be good to add to the documentation that users should expect that sources are written for the latest version of a given command unless otherwise specified.

**Comment by jose-elias-alvarez** [comment]
In 0c2eab0a7c7389b01b9c326bac30782fb5687e11 I added a note to the built-ins documentation about the `$PATH` requirement, and f1a2eaba4f00b7ff2729aed48ea98585413c9f39 improved the error message shown when a command isn't executable. Hopefully that's good enough for now!
