### ISSUE TITLE
[Bug]: Filetypes table of user config thrown away by `validate_config` function.

### ISSUE THREAD

**Issue by sandersantema** [jose-elias-alvarez/null-ls.nvim#13]
So I've got the following configured in my lsp setup for null-ls:

``` lua
    null_ls.setup({
        ...
        filetypes = {
            "python",
            "lua",
        },
        ...
    })
```

I've left out some unrelated configuration and replaced it with `...`

The `filetypes` table is however thrown away by the `validate_config`
called by the `setup` function in `lua/null-ls/config.lua`. Which means
null-ls is activated for every single filetype. Currently I'm using the
following workaround:

``` lua
M.setup = function(user_config)
    if config._setup then
        return
    end

    -- USER: FIXME: function validate_config throws away the filetypes key in
    -- user config so store it here and set it again later for now
    local filetypes_workaround = user_config.filetypes

    local validated = validate_config(user_config)
    config = vim.tbl_extend("force", config, validated)
    
    -- USER: FIXME: see line 172
    config.filetypes = filetypes_workaround

    if config.sources then
        register(config.sources)
    end
    config._setup = true
end
```

But I suppose this should be fixed in the `validate_config` function. On
another note, I think the user should also be able to configure which
capabilities null-ls should have for a file type. Even though I'm only
using null-ls for formatting it seems to register itself with code
actions and diagnostics capabilities too. Although automatically setting
the right capabilities I think the user should be able to configure it
manually first and foremost so that you for instance can disable
something temporarily when working with certain files or if a particular
tool is not working correctly.

**Comment by jose-elias-alvarez** [comment]
1. The goal of not enabling a `filetypes` key in `setup` was to simplify the process by inferring enabled filetypes from the user's sources. I missed a `_` in a variable name, so this check wasn't actually working correctly, but I just pushed a commit which should take care of the issue and only enable null-ls for filetypes with a defined source. Let me know if the latest version takes care of the issue for you.

2. Unfortunately, adding in per-filetype capability configuration would be pretty tricky, since there's no way for the client and server instances to communicate with each other until the LSP server has been started, at which point the server has already defined its capabilities. There is an [open PR](https://github.com/neovim/neovim/pull/13642) to add dynamic registration to Neovim, which I definitely want to implement once it's ready, but until then, I don't know if this is really possible.

My focus so far has been on making sure null-ls behaves properly when handling requests for its supported methods, regardless of whether a given filetype has sources defined methods. If you run into cases where it doesn't, please let me know!

**Comment by sandersantema** [comment]
Sounds good for now, I'll test these your fix out in a bit. Shame that PR didn't get in earlier, I suppose it won't for 0.5 stable either, guess I'll be running HEAD for a little longer :)

**Comment by sandersantema** [comment]
Ok, so I tried it out and it seems that this fixes the filetype issue but I've found (or so I think) a different issue.
