### ISSUE TITLE
sources args does not support `~`

### ISSUE THREAD

**Issue by funn1est** [jose-elias-alvarez/null-ls.nvim#138]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.0-dev+198-g81f4de08bd

### Steps to reproduce

config

```lua
local null_ls = require('null-ls')
local b = null_ls.builtins

local sources = {
  b.formatting.stylua.with({
    args = { '--config-path', '~/.config/stylua.toml', '--stdin-filepath', '$FILENAME', '-' },
  }),
}

null_ls.config({
  debug = true,
  sources = sources,
})
```

### Expected behavior

support `~` in args

`args = { '--config-path', '/home/user/.config/stylua.toml', '--stdin-filepath', '$FILENAME', '-' }` worked

### Actual behavior

sources args does not support `~`

### Debug log

```bash
received LSP request for method textDocument/formatting
running generators for method NULL_LS_FORMATTING
spawning command stylua with args:
{ "--config-path", "~/.config/stylua.toml", "--stdin-filepath", "/home/user/.dotfiles/
nvim/.config/nvim/lua/config/lsp/init.lua", "-" }
error output: Failed to read config file: No such file or directory (os error 2)
output: nil
received edits from generators
{}
```

### Help

No

**Comment by jose-elias-alvarez** [comment]
It's interesting that this doesn't work, since the arguments should be passed to the formatter as-is, and when called directly from the command line with the same arguments, everything works as expected. I thought it might be an env issue, but that doesn't seem to be the case. 

I need to look into this more (it may just be a quirk of how `luv` spawns processes) and see if there's a clean fix. If not, I think we might just have to leave this as-is and document that users should use absolute paths.

**Comment by jose-elias-alvarez** [comment]
I added a mention of the issue and the workaround in 4dc80c92ea231b7d9688d998b838d9cb953b320f (it turns out `vim.fn.expand` can expand `~` too, which is handy). Thanks for reporting this!
