### ISSUE TITLE
null-ls attaches to every buffer

### ISSUE THREAD

**Issue by folke** [jose-elias-alvarez/null-ls.nvim#15]
First of all, thank you for this amazing plugin!

Right now it seems that null-ls attaches to every buffer including for example Nix buffers.

I would expect it to only attach to the buffers with a filetype from one of the sources.

I run setup with `{}` and only use it with your `ts` plugin.

Is this behavior expected?

**Comment by jose-elias-alvarez** [comment]
Hey! You're right about the expected behavior, and in fact Ipushed a commit in the past couple of days that solved an issue causing null-ls to attach to all buffers. Are you still seeing this behavior on the latest commit?

**Comment by folke** [comment]
Sorry, forgot to close this one. Works as expected! Thanks!

**Comment by nghialm269** [comment]
hi @jose-elias-alvarez, I'm getting the same issue, I'm using dartls ([akinsho/flutter-tools](https://github.com/akinsho/flutter-tools.nvim))

I have this autocmd to run format on save when in dart buffer:
```vim
autocmd BufWritePre *.dart lua vim.lsp.buf.formatting_sync({}, 200)
```

Every time I save a dart buffer, neovim prompts me to choose between `dartls` and `null-ls`.

I also see `null-ls` in `:LspInfo` output.

How do I make `null-ls` ignore every filetype but the ones in the `null-ls` configuration?

My `null-ls` config:
```lua
local null_ls = require("null-ls")
local sources = {
	null_ls.builtins.formatting.stylua,
	null_ls.builtins.code_actions.gitsigns,
}
null_ls.setup({ sources = sources })
```
I also use your `nvim-lsp-ts-utils` plugin to integrate `eslint` and `prettierd` with null-ls.

**Comment by jose-elias-alvarez** [comment]
@nghialm269 Judging from your config, your issue is actually a bit different – it's because the Gitsigns builtin is enabled for all filetypes by default, and null-ls currently cannot recognize that it's not able to respond to the formatting request. This is something I want to work on when I have a little time, though, so I've opened up #28.

**Comment by nghialm269** [comment]
@jose-elias-alvarez you're right, disable gitsigns works.

I enable gitsigns' code action because I'm curious what it provides, I don't actually use it so disabling it is fine for me.

Thanks for the quick help and great plugin, it's faster than `efm` and easier to config IMO, hope it will get more mature in the future.
