### ISSUE TITLE
Support for pmd/cpd static analysis tool

### ISSUE THREAD

**Issue by krishnakumarg1984** [jose-elias-alvarez/null-ls.nvim#1582]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Please support the pmd/cpd static analysis tool which supports multiple programming languages.

https://pmd.github.io/ 

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by IlyasYOY** [comment]
Hello! PMD is [supported](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#pmd).

The problem is that PMD 7.0 breaks compatibility with current integration. The simplest solutions is to install version 6.x. Also you might implement integration with PMD 7 yourself, the steps are described [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md) and [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/HELPERS.md).

**Comment by krishnakumarg1984** [comment]
Thank you
