### ISSUE TITLE
Maintain file endings on `to_temp_file`

### ISSUE THREAD

**Issue by meck** [jose-elias-alvarez/null-ls.nvim#159]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I'm adding [this linter](https://github.com/priv-kweihmann/oelint-adv) to my editing setup. However it only takes files not stdin as input. This would work fine with `to_temp_file` however the linter uses the file-endings to categorize input files, since `to_temp_file` uses the format `/tmp/lua_XXXX` this brakes things.

One possible solution would be to fetch the `bufname` and add to the temp file name e.g. `/tmp/lua_XXXoriginalfilename.orgend`  

### Help

Yes

### Implementation help

Not to familiar with lua, but i could give it a go, but it might be an easy fix for someone else...

**Comment by jose-elias-alvarez** [comment]
So if the extension matches, the source will work? This might be a little tricky. We're currently using Lua's `os.tmpname`, which doesn't have any configuration (and just attaching an extension to the temp path doesn't work, sadly). 

Since neovim/neovim#14985 was merged, we could try to use `uv.fs_mkstemp` when Neovim has access to it, but as far as I can tell that still requires a template that ends in `XXXXXX`, so adding an extension doesn't work. Let me look into this a bit more and get back to you.
