### ISSUE TITLE
Expected table got null

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/null-ls.nvim#16]
Hey, thanks for the cool plugin.

I'm using it in fairly large codebases and seeing some random weird errors from time to time so ill try to post what happens.

This is the one that pops up quite often after pasting some code in.

In this specific case, all I did was paste code from line 66 to 70 (useFieldArray hook). Let me know if I can provide any other info to help debug this.

![image](https://user-images.githubusercontent.com/8104698/122914145-a1ccc100-d35a-11eb-9e35-c75e22ed6f8b.png)

**Comment by jose-elias-alvarez** [comment]
Thanks for helping test the plugin on a larger codebase – my own work is pretty small-scale, so I'm sure there's a lot of cases I haven't handled.

In this case, I think the issue is with the code action creation logic in nvim-lsp-ts-utils. I haven't been able to replicate the precise error in your screenshot, but based on the stack trace, I think [this commit](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/commit/260ea7b7a7346d331df0c69ad19b2f42f888c853) should take care of it. Let me know if that works.

**Comment by vuki656** [comment]
Seems to have fixed the common places where it occurred. Thanks.

Also, each time I do `PackerSync` it's asking me if it can delete `null-ls`.

![image](https://user-images.githubusercontent.com/8104698/122961515-c3db3900-d384-11eb-9001-692a8f422101.png)

Should I open a separate issue to track that?

**Comment by jose-elias-alvarez** [comment]
Great! No idea about the Packer issue, though. null-ls doesn't do anything special in terms of plugin management, so I don't know if it's related. 

I found [this issue](https://github.com/wbthomason/packer.nvim/issues/156) that seems to describe a similar situation, and I've also personally had to wipe out my plugin directory a couple of times to solve Packer issues, so I'd give that a shot, too. Feel free to open an issue if nothing seems to help and we can try to figure it out.

**Comment by vuki656** [comment]
It's prob an upstream issue then. Thanks for the help anyways.
