### ISSUE TITLE
Make possible to create formatter using a temp file

### ISSUE THREAD

**Issue by gbprod** [jose-elias-alvarez/null-ls.nvim#167]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I'm trying to add a formatter ([php-cs-fixer](https://github.com/FriendsOfPhp/PHP-CS-Fixer)) but I can't use stdin. Currently, I use https://github.com/mhartington/formatter.nvim and I've set it up to use a temp file : 

```lua
require('formatter').setup({
  logging = false,
  filetype = {
    php = {
      function()
        return {
          exe = 'php-cs-fixer',
          args = {
            '--using-cache=no',
            '--no-interaction',
            '--quiet',
            'fix',
          },
          stdin = false,
          tempfile_dir = "/tmp"
        }
      end
    }
  }
})
``` 

When I try to do the same with null-ls, seems that the temp file is correctly created and the formatter is correctly applied to it but the content is not copied to the buffer.

```lua
M.phpcsfixer = h.make_builtin({
    method = FORMATTING,
    filetypes = { "php" },
    generator_opts = {
        command = 'php-cs-fixer',
        args = {
            '--using-cache=no',
            '--no-interaction',
            '--quiet',
            'fix',
            "$FILENAME",
        },
        to_stdin = false,
        to_temp_file = true,
    },
    factory = h.formatter_factory,
})
```

Is it possible to add this possibility ?

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I can try to fix it but I don't know where we should do the copy... :sweat_smile:

**Comment by jose-elias-alvarez** [comment]
This is a great idea. Could you try [this branch](https://github.com/jose-elias-alvarez/null-ls.nvim/tree/formatting-from-temp) and see if it works for you? My idea was to add a new `from_temp_file` flag and automatically set it to `true` when using `formatter_factory` and setting `to_temp_file = true` (since that's the only way formatting with temp files will work). 

The directory thing is still an issue, since I realized that `uv.fs_mkstemp` creates the temp file at the current working directory, which isn't ideal. I want to test this out on Windows later this month when I have access to a PC and see if I can come up with a cross-platform solution.

**Comment by gbprod** [comment]
Works like a charm ! When you merge this branch I'll create a PR for introducing php-cs-fixer :)

About directory issue, maybe we could add an option to set the temp directory ? [formatter.nvim](https://github.com/mhartington/formatter.nvim) do this.

**Comment by jose-elias-alvarez** [comment]
Great! I prefer to keep it as a default for now, since I think that'll be fine for 99% of users, but if there's demand for an option in the future we can consider it. (In 7f60529105aabaa5029903640396613fb6e3f2fc I added a default that should hopefully work for both Unix and Windows, but I'll have to wait until later this month to test it myself.) 

I'll create a PR for the branch and merge it once I've written test coverage, which shouldn't take too long.

**Comment by gbprod** [comment]
Thanks !
