### ISSUE TITLE
Option to set neovim path

### ISSUE THREAD

**Issue by oponkork** [jose-elias-alvarez/null-ls.nvim#173]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I have installed neovim on remote servers by downloading the appimage and extracting it somewhere. The installation directory is not in my path, rather I have an alias set to it. With null-ls I get the following error: 
```
cmd["nvim"] is not executable.
```
Which is expected as nvim is not in my path. When I add the neovim directory to `PATH` it works fine. Would it be possible to have a config option to set the path to nvim binary?

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by jose-elias-alvarez** [comment]
This should definitely be possible. We can modify the command via lspconfig by setting `require("lspconfig")["null-ls"].setup({ cmd = { "/path/to/nvim" } })`. However, we’d also have to change the check on [this line](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/5d82f9c50cd89e2a0c63ca761024f764225c1d1e/lua/null-ls/rpc.lua#L24), since it’s currently hard coded to `"nvim"`. We’d have to get the current null-ls config from lspconfig and check the command at that point to make sure it matches. 

If you feel up for it, feel free to look into it and put in a PR if you figure out a solution. Otherwise, I won’t have access to a computer for about a week, but I’ll check this out when I can.

**Comment by oponkork** [comment]
Thanks a lot for your reply. I will try to get it working.
