### ISSUE TITLE
Enable excluding filetypes

### ISSUE THREAD

**Issue by bnjmnt4n** [jose-elias-alvarez/null-ls.nvim#20]
I enabled the `gitsigns` code actions, which works great for all my code files. However, on some filetypes, such as Neogit, I get an error when the generator tries to get a code action for a non-existent file.

Is it possible for filetypes to be enabled for "*" except for a few?

**Comment by jose-elias-alvarez** [comment]
By default, null-ls will only generate code actions when you specifically request them. Are you using a plugin like [nvim-lightbulb](https://github.com/kosayoda/nvim-lightbulb) that requests them automatically? If so, is it possible to configure excluded filetypes on their end? 

It's definitely possible to add some kind of exclusion syntax, but I want to make sure that we've looked into other possible solutions first.

**Comment by bnjmnt4n** [comment]
You're exactly right, I'm using nvim-lightbulb which requests code actions automatically. I think it should be a relatively simple fix to avoid requesting code actions based on the current filetype. Thanks for the tip, I'm relatively new to Neovim and Lua, so it didn't occur to me about checking my other plugins. I'll play around with my config and post a solution if I find one. I agree that it's probably best to keep null-ls simple and avoid adding extra complexity if it can be handled easily elsewhere.

**Comment by jose-elias-alvarez** [comment]
From what I can tell, given the current configuration options for this plugin and for nvim-lightbulb, you'd have to specifically declare a list of "approved" filetypes on one side, which is annoying. 

In this case, I think that the issue is actually with the way we generate code actions for Gitsigns, since their API wasn't written with the expectation of attempting to get actions for nonexistent files. I just pushed a simple fix that'll prevent error messages, so could you try updating when you get a chance and let me know if that takes care of the issue?

**Comment by bnjmnt4n** [comment]
Thanks, that fixes the issue.

My alternative solution was to use a wrapper around calling the update lightbulb method:

```lua
UpdateLightbulb = function()
  if vim.bo.filetype ~= "Neogit" then
    require('nvim-lightbulb').update_lightbulb()  
  end
end
```

 But this would require hardcoding a list of excluded filetypes as well.
