### ISSUE TITLE
eslint diagnostics

### ISSUE THREAD

**Issue by gegoune** [jose-elias-alvarez/null-ls.nvim#21]
Great project! Works really nice.

Given existence of https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils, would you be willing to add eslint (eslint_d actually) diagnostics to null-ls? I want to use it for Vue files and doubt enabling tsserver for them is a good idea

**Comment by jose-elias-alvarez** [comment]
Sure, I could port the implementation of diagnostics as a built-in (I wouldn't port code actions, since they're far more complex). I'm still making some changes to ESLint sources and am not yet 100% confident about their stability, but once I am, I'll work on this.

In the meantime, if you're interested, I can modify the null-ls implementation in nvim-lsp-ts-utils to allow direct configuration, meaning you'd be able to do something like this (independent of tsserver):

```lua
require("nvim-lsp-ts-utils.null-ls").setup({ eslint_enable_diagnostics = true, filetypes = { "vue" } })
```

Let me know if you're interested and I can put something together.

**Comment by gegoune** [comment]
That would be really nice! Could use intervention from other plug-in for the time being.

**Comment by jose-elias-alvarez** [comment]
Not sure if I understand completely, but nvim-lsp-ts-utils hooks into null-ls to provide diagnostics (among other things). At the moment, though, it's closely coupled to `tsserver`, and I don't work with Vue, so I can't say anything about compatibility.

In the end, porting diagnostics was easier than isolating the null-ls module in ts-utils, so I just pushed 40d6cb2f6e0609e6341ac89f448e7d43f35506a9. After updating to the latest version of null-ls, you should be able to enable eslint_d diagnostics for supported filetypes with the following snippet:

```lua
local null_ls = require("null-ls")

local sources = { null_ls.builtins.diagnostics.eslint.with({ command = "eslint_d", filetypes = { "vue" } }) }
null_ls.setup({ sources = sources })
```

Could you let me know if that works? I don't have any Vue files to test it on, but you're able to lint Vue files from the command line, the setup above should work.

**Comment by gegoune** [comment]
I have just tested it and can confirm it's working as expected. Thank you very much for super quick fix, this is amazing.

What I meant in my edit in post above was that maybe in nvim-lsp-ts-utils you could just call null-ls' eslint_d diagnostic, since it's there and maybe don't need to have that code in nvim-lsp-ts-utils as well, but I don't know how those plugins are set up so might just be talking nonsense.

Anyway, null-ls is awesome and once again, thanks for resolving it quickly!
