### ISSUE TITLE
[Feature Request] support for `textDocument/rangeFormatting`

### ISSUE THREAD

**Issue by MunifTanjim** [jose-elias-alvarez/null-ls.nvim#22]
I tried to implement it myself. But got stuck because the expected type of `args` is `table`:

https://github.com/jose-elias-alvarez/null-ls.nvim/blob/40d6cb2f6e0609e6341ac89f448e7d43f35506a9/lua/null-ls/helpers.lua#L84

But for rangeFormatting, the formatter needs to know about the range. e.g. for `prettier`, we need to pass [two args](https://prettier.io/docs/en/options.html#range) `--range-start` and `--range-end`.

If you point me to how you want to handle this, I can create a PR with the changes.

**Comment by jose-elias-alvarez** [comment]
Maybe I'm misunderstanding the issue, but couldn't you combine all of the args into a single table?

```lua
local args = { 
"--range-start", 5, 
"--range-end", 10
... -- other args 
}
```

I'm definitely in support of adding the feature. These are the changes I'd want make to the current built-in structure in order to support this cleanly:

1. We'd want to let `args` be a function that takes `params` as an argument and returns a table of arguments to pass to the command. This would also let a single built-in handle both range formatting and standard formatting by checking the method of the request. 
2. We'd then need to pass position information in `params` to the argument generator. I don't know much about `textDocument/rangeFormatting`, but I assume that information is passed to the server in the request, so it shouldn't be hard to get it. 
3. Since many formatters don't support range formatting, we'd want them to explicitly declare support for the method. I think the simplest way would be to let `method` be a list of supported methods and check it accordingly when receiving requests.
4. We'd have to modify `formatter_factory` to check `params` for position information, since at the moment it assumes we always want to replace the whole document. 

Feel free to put in a WIP PR whenever and I'll review it.

**Comment by MunifTanjim** [comment]
> Maybe I'm misunderstanding the issue, but couldn't you combine all of the args into a single table?

The args is supplied at the time of setup, right? So it's fixed. But the range args needs to be passed when rangeFormatting is invoked.

> We'd want to let args be a function that takes params as an argument

Yeah, that's exactly what I had in mind. Thanks for the pointers. I'll create a WIP PR with these.
