### ISSUE TITLE
Gitsigns builtin causes notification `Autostart for null-ls failed: matching root directory not detected.`

### ISSUE THREAD

**Issue by mrjones2014** [jose-elias-alvarez/null-ls.nvim#336]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.5.1

### null-ls config

local null_ls = require('null-ls')
local b = null_ls.builtins

local sources = {
  b.code_actions.gitsigns,
}

null_ls.config({
  sources = sources,
})

require('lspconfig')['null-ls'].setup({})

### Steps to reproduce

With the `null-ls` config above, just open Neovim.

### Expected behavior

You don't get the notification: `Autostart for null-ls failed: matching root directory not detected.`

### Actual behavior

You get the notification: `Autostart for null-ls failed: matching root directory not detected.`

### Debug log

Not really anything relevant as far as I can tell:

```
[DEBUG Thu Nov 11 14:47:58 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP request for method initialize
[DEBUG Thu Nov 11 14:47:58 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method initialized
[DEBUG Thu Nov 11 14:47:58 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method textDocument/didOpen
[DEBUG Thu Nov 11 14:47:58 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Thu Nov 11 14:47:58 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: spawning command luacheck with args:
[DEBUG Thu Nov 11 14:47:58 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: { "--formatter", "plain", "--codes", "--ranges", "--filename", "/Users/mat/.config/nvim/lua/lsp/null-ls.lua", "-" }
[DEBUG Thu Nov 11 14:47:59 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: error output: nil
[DEBUG Thu Nov 11 14:47:59 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: output: nil
[DEBUG Thu Nov 11 14:47:59 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received diagnostics from generators
[DEBUG Thu Nov 11 14:47:59 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: {}
[DEBUG Thu Nov 11 14:48:08 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP request for method shutdown
[DEBUG Thu Nov 11 14:48:08 2021] ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:74: received LSP notification for method exit
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I'm not super familiar with the LSP API or how Gitsigns integrates with it.

**Comment by jose-elias-alvarez** [comment]
Hmm, I'm unable to reproduce this on my end on 0.5.1 and nightly. The error is coming from lspconfig, and there have some changes there recently. Are you using the latest version of both plugins?

Gitsigns is enabled for all filetypes by default, and it looks like this issue is caused by trying to attach to buffers without a root directory, which shouldn't be happening. Is this a recent issue? We haven't made any changes that should affect this, but if you've only started experiencing it recently, a bisect would be very helpful.

**Comment by jose-elias-alvarez** [comment]
I ran into this issue while working on something else and noticed that because of [this line](https://github.com/neovim/nvim-lspconfig/blob/2589549ed16a605cd52f8c8d55aa00d413956834/lua/lspconfig/configs.lua#L103), lspconfig now shows a (somewhat confusing) message when it can't resolve a file's root directory (it used to return silently). c1b6068a64c5f303b627d71c5d9f93d1b717dd0b checks that the buffer has a name before sending it to lspconfig, so I think this'll help. Can you try updating and let me know if you still see the error (and also confirm whether the error was specific to dashboard or happened with other files)?

**Comment by mrjones2014** [comment]
That seems to have fixed it! 🚀
