### ISSUE TITLE
Add ability to catch more flake8 codes

### ISSUE THREAD

**Issue by bwells** [jose-elias-alvarez/null-ls.nvim#365]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Flake8 has a somewhat unusual severity/coding system in that it does not provide a more traditional info, warn, error style of message classification. The code system instead tags the origin of which flake8 plugin generated the diagnostic message. 

This presents a couple of difficulties when combined with null-ls. There doesn't seem to be an out of the box way to modify the `on_output` setting of a builtin, requiring replacing the entire builtin if you wanted to change the severity listing of a default source (in my case move F messages to warning or error). 

Additionally, flake8 has an extensive set of plugins which provide their own letter prefixes (bugbear for example uses B). The existing builtin ends up ignoring these messages as there is no default or catch-all severity handler. 

Neither of these is particularly problematic for me to work around as the solution to both is define my own diagnostic source based on the builtin, but there could be room for improvement. 

See https://flake8.pycqa.org/en/latest/user/violations.html#selecting-violations-with-flake8 and https://flake8.pycqa.org/en/latest/user/error-codes.html for some references on flake8 codes.

and https://github.com/PyCQA/flake8-bugbear

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

A simple solution that would get most people 99% of the way there would perhaps be just to audit the existing flake8 plugin ecosystem and provide default severities for each currently used letter prefix code. It might also be preferable to change the current default severity of the F codes in particular, but it may be undesirable to make that change for other existing users. 

If we'd like to provide defaults for more error codes out of the box I'd be happy to do that leg work and upstream it.

**Comment by jose-elias-alvarez** [comment]
> The existing builtin ends up ignoring these messages as there is no default or catch-all severity handler.

I could have sworn this was handled by #253?

As a non-Python user, this sounds like a complicated situation, since there's no objective way for us to map these to severities. Allowing users to override `on_output` is possible, but at that point I'd prefer that they either upstream their improvements or create a custom source entirely. 

I think making sure that we're handling common plugins (and encourage further contributions if users find that a plugin they rely on is missing) is probably the best we can do in terms of out-of-the-box behavior. A PR would be very appreciated.
