### ISSUE TITLE
Unable to get misspell to work

### ISSUE THREAD

**Issue by gegoune** [jose-elias-alvarez/null-ls.nvim#43]
I have added misspell to my configured source, installed it with go but can't get it to pick up any misspellings from comments or strings in lua files. Should it work that way?

**Comment by gegoune** [comment]
Ah, seems to work after all, not sure why I didn't see some test errors why trying strings like 'asasgsdfg'. :)

**Comment by gegoune** [comment]
Have noticed that diagnostic doesn't get cleared once misspelling is corrected. So will reopen this issue for now.

**Comment by jose-elias-alvarez** [comment]
Thanks for checking on this! I see the same behavior, and I believe the issue was caused by the fact that `misspell` seems to read the actual file from the disk if you specify a filename in the arguments, even if you pipe the current buffer content to `stdin`. 

Could you update and let me know if it works as expected now?

**Comment by jose-elias-alvarez** [comment]
Update: my fix inadvertently created a [separate issue](https://github.com/folke/trouble.nvim/pull/67) with trouble.nvim, but hopefully the behavior of the actual source should be okay.

**Comment by gegoune** [comment]
Clearing of diagnostics seems to be fixed now, nicely done Jose, thanks! Feel free to close it or wait for trouble issue to be fixed before doing so.
