### ISSUE TITLE
Provide config option to disable errors when a linting or formatting tool is not installed

### ISSUE THREAD

**Issue by krishnakumarg1984** [jose-elias-alvarez/null-ls.nvim#528]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

In a typical scenario, we use the same `init.lua` configuration ported across multiple machines. In my case, in my work/personal laptops, I have all the formatting and linting tools installed. 

However, I have to do remote development on various machines in which the linting/formatting binaries may not be installed (or even installable (even if I had sudo privilege, certain command-line tools do not compile on architectures such as ARM or MIPS, or a cross-compiling toolchain may not be always available). 

In circumstances where an executable is not found in $PATH, the current behaviour of `null-ls` is to throw a bright red error every single time the file is saved (when format-on-write is configured). This gets annoying very quickly (since I am already aware of the fact that the relevant executable is not in $PATH, or can obtain that info through `:checkhealth`).  

Please provide a config option to disable the error when a relevant executable is not available in `$PATH`. This config option could be something like:
``` lua
executable_not_found_error: false   -- default is true 
```
You could leave the default as true to maintain compatibility with existing configs. 

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I am not sure how to do this. I have never used lua before other than to configure neovim!

**Comment by jose-elias-alvarez** [comment]
First: On the latest version of null-ls, you should only see the error once, since the source will deregister itself after an error. Is that not the case for you? 

Second: Suppressing the error is of course possible, but it's not a straightforward solution. Since users can set commands dynamically, we can only check if commands are executable when they're run (not on startup or registration, which would also add startup time). Simply suppressing the error will create weird situations where null-ls thinks it can do something because it has a registered source for that method, but it actually can't because the command is not executable, (though it doesn't know that yet).

The best way we have to handle this now is through `condition`. You can do this as a one-off like this:

```lua
local null_ls = require("null-ls")

local sources = {
    null_ls.builtins.prettier.with({
        condition = function()
            return vim.fn.executable("prettier") > 0
        end,
    }),
}
```

You could also generalize this with a helper:

```lua
local null_ls = require("null-ls")

local wrap_builtin = function(builtin)
    local command = builtin._opts.command
    builtin.condition = function()
        return vim.fn.executable(command) > 0
    end
    return builtin
end

local sources = {
    wrap_builtin(null_ls.builtins.formatting.prettier),
}
```

**Comment by bpinto** [comment]
If you don't need a dynamic check, one could also write it like so:

```
local sources = {
  null_ls.builtins.formatting.eslint_d
}

if vim.fn.executable('prettier_d_slim') == 1 then
  table.insert(sources, null_ls.builtins.formatting.prettier_d_slim)
end

null_ls.config({ sources = sources })
```

**Comment by korney4eg** [comment]
Can you tell me how can I dynamically disable/enable linting highlight ?

**Comment by jose-elias-alvarez** [comment]
@korney4eg The [sources API](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/SOURCES.md) lets you enable and disable sources at will. If that doesn't do what you want, can you open a discussion and describe more thoroughly the behavior you're looking for? It's not really related to this issue.

**Comment by korney4eg** [comment]
Thanks @jose-elias-alvarez for info.
So for anyone that is interested, for me worked:
* to disable
```viml
:lua require("null-ls").disable({})
```
* to enable
```viml
:lua require("null-ls").enable({})
```

**Comment by jrafaaael** [comment]
same error here. I can't disable null-ls as say @korney4eg because I want to use prettier...
![Screenshot_2022-04-01_21-33-25](https://user-images.githubusercontent.com/70046023/161360597-e4020d1b-5add-4303-b748-b8f68216a1c8.png)

**Comment by jose-elias-alvarez** [comment]
Having thought about this more, I don't think I'd be interested in adding this as a config option because I suspect it'll lead to situations where users don't know why a source is working. Since this issue was opened, we implemented the [source API](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/SOURCES.md), which makes it easier to register and manipulate sources dynamically. I think the right solution for our architecture is to check whether sources are conditional before registering them, vs. registering them unconditionally and suppressing errors when they can't run.
