### ISSUE TITLE
[RFC] Parsable metadata for auto-generated docs and interop

### ISSUE THREAD

**Issue by kylo252** [jose-elias-alvarez/null-ls.nvim#552]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

As mentioned in https://github.com/jose-elias-alvarez/null-ls.nvim/pull/397, 
> We already have an issue with built-in documentation falling out of sync, so I've been thinking about automatically generating that, too.

I think we'd need some sort of manifest, containing the rest of the hard-coded information that is mentioned in [BUILTINS](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md), such as: description, URL, supported features(?)

Another interesting part would be exposing how that source can be installed, for example: `npm install markdownlint-cli`. This is pretty useful to have interop with https://github.com/williamboman/nvim-lsp-installer which offers a APIs that should be able to handle most common installation methods, @williamboman 👋 

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I'm not sure what the best presentation of that manifest should look like. The simplest solution is probably a basic json/lua table with desired entries, à la NoSQL.

What do you guys think?

**Comment by jose-elias-alvarez** [comment]
I think Lua tables make sense, since null-ls is tightly coupled to Neovim and its ecosystem. The current information in BUILTINS.md is *mostly* standardized, so I imagine each entry could look like this:

```lua
local metadata = {
    ["markdownlint"] = {
        -- pull these from the existing metadata (or the built-in itself)
        filetypes = { "markdown" },
        command = "markdownlint",
        args = { "--stdin" },
        supported_methods = "diagnostics",

        -- manually entered
        description = "`markdown` style and syntax checker.",
        url = "https://github.com/igorshubovych/markdownlint-cli",

        -- optional
        install_command = "npm install -g markdownlint-cli",
        -- we can convert these into an unordered list?
        notes = {
            "Something special about the source (e.g. if it requires a config file)",
        },
    },
}
```

**Comment by williamboman** [comment]
As for describing installation method: For making it platform agnostic and programmatically parseable I think it'd be preferred if it was expressed through some table schema, rather than a shell command, something like so:

```
installation_method = {
    type = "npm",
    packages = { "markdownlint-cli" }
}
```

For the purpose of readability, this could then be translated in null-ls docs to `npm install -g markdownlint-cli`. This might be duplicated effort, but if there's an interest to provide the installation command in null-ls, might as well go all the way?

**Comment by jose-elias-alvarez** [comment]
I came across [this plugin for installing formatters](https://github.com/PlatyPew/format-installer.nvim), which definitely seems like it could make use of the installation method metadata, too. @PlatyPew Feel free to add any thoughts / feedback on this you might have.

**Comment by mvllow** [comment]
Could we keep metadata in comments and parse that out? Eg. in `lua/null-ls/builtins/diagnostics/eslint.lua`

```lua
-- name: eslint
-- desc: A linter for the `javascript` ecosystem.
```

And the default args could be parsed from the file for a single source of truth

**Comment by jose-elias-alvarez** [comment]
> Could we keep metadata in comments and parse that out? Eg. in `lua/null-ls/builtins/diagnostics/eslint.lua`
> 
> ```lua
> -- name: eslint
> -- desc: A linter for the `javascript` ecosystem.
> ```
> 
> And the default args could be parsed from the file for a single source of truth

This might make sense, especially given that we have [built-ins that are derivatives of other built-ins](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/code_actions/eslint_d.lua). Including the metadata in the options table passed to `make_builtin` would require us to add metadata-specific logic into the core code, which isn't ideal. Is there a good way to parse these docstrings that I'm not aware of? Treesitter might work but I'm not familiar with the API.

Either way, I'd like to start working on this soon, since writing and maintaining documentation is becoming a larger and larger burden. If no one has any additional feedback for now, I'll open up a PR this weekend.
