### ISSUE TITLE
Support for sequential formatting when there are multiple formatters enabled for a file type

### ISSUE THREAD

**Issue by nghialm269** [jose-elias-alvarez/null-ls.nvim#56]
For example, in Python, I want to run `black` to format the buffer and then `isort` to organize the import.

**Comment by jose-elias-alvarez** [comment]
Note to self (or anyone who wants to put in a PR): 

My tentative idea for implementing this is to add a `run_and_get_next` method for generators, which will run the generator for a given method at a specific index and return the index of the next available generator (or `nil` if there is none). We can then run a loop in the formatting handler to repeat the formatting process (updating the text content after the first run) until we've gone through all the available generators. 

This should make it so that formatters will run in the order they've been defined by the user, which should line up with average user expectations. Cases where only one formatter is registered will be unaffected, and as long as we avoid getting content unless necessary, there won't be any sort of performance hit. 

The behavior might be weird if a user has defined their own formatters and is also using an integration that adds a formatter (though that's an unlikely case) and might also break some exotic custom handlers, but since we're already pretty far from default formatting behavior, I'm not too worried. I have a mountain of stuff to work on (not to mention my actual job) but unless someone puts in a (much-appreciated!) PR, I hope to get around to this later this month.
