### ISSUE TITLE
Diagnostic in closed buffers typescript

### ISSUE THREAD

**Issue by timsofteng** [jose-elias-alvarez/null-ls.nvim#609]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

May I somehow open list with buffers which contain errors if they wasn't opened in vim?
I've installed `tsc` and worked with typescript files.

Imagine you open some file with component which has no required props and make it required.
You'll have bunch of errors in another components which don't send this props to this components.
Can I open this files with `null-ls` diagnostic?

### Help

No

**Comment by gegoune** [comment]
Have a look if Folke's trouble.nvim does what you are after.

**Comment by timsofteng** [comment]
> Have a look if Folke's trouble.nvim does what you are after.

Doesn't work...
Troubles not detected those files which are not opened in nvim...

**Comment by vuki656** [comment]
I think this is due to `tsc` itself not checking files not yet opened. 

Also, what you have mentioned, making props required, would cause a typescript error. Null ls handles diagnostics and formatting from external tools like eslint and prettier.

**Comment by timsofteng** [comment]
> I think this is due to `tsc` itself not checking files not yet opened.
> 
> Also, what you have mentioned, making props required, would cause a typescript error. Null ls handles diagnostics and formatting from external tools like eslint and prettier.

I don't know how tsc works but I definitely can see error in closed files in `yarn start` terminal window.
The main idea is to keep terminal with yarn local server closed. I should keep it open now because error could happen in any files closed or open.

**Comment by vuki656** [comment]
I assume your `yarn start` command invokes `tsc` which will try to compile the **whole** project and then run it, hence if there is any file that contains typescript errors, you will see them.

You are confusing what `tsc` aka typescript compiler does, and what `null-ls` does.

`tsc` is concerned whether or not the code is syntactically correct, meaning can it actually be ran. If you have a missing import, `tsc` won't know where to find the file and that makes the code incorrect hence it reports an error in any file across the project when you invoke `yarn start`.

`Null-ls`'s only concern is connecting external tools to lint and format the code.

If `null-ls` reports some errors by a linter, say eslint, and typescript doesn't report any errors. Your code is still syntactically valid and can be executed regardless of what null-ls says.   

Another important thing is that `null-ls` attaches to your open buffers and not all files in the whole project. This is also true for the `typescript-language-server`, because if it were to attach to every single file in your project that would be a performance hog and not sustainable.

**Comment by jose-elias-alvarez** [comment]
I haven't really looked at the discussion, but we have a [`tsc` built-in](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#tsc) that parses errors from `tsc`, including files that haven't yet been opened in Neovim. Does that do what you want?

**Comment by timsofteng** [comment]
> I haven't really looked at the discussion, but we have a [`tsc` built-in](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#tsc) that parses errors from `tsc`, including files that haven't yet been opened in Neovim. Does that do what you want?

Sounds like yes, they do.
Can you help me please to configure it? I've installed TSC and enabled diagnostic TSC. What should I do next?

**Comment by jose-elias-alvarez** [comment]
Assuming you've added it to your list of sources and it's shown as an active source when you run `:NullLsInfo`, it should generate diagnostics when you open or save files. You can populate the quickfix list with diagnostics for all files with errors using `:lua vim.diagnostic.setqflist()` or use a plugin like trouble.nvim.

Note that the behavior of the built-in is a little weird, since it assumes that the user is also running `typescript-language-server` and attempts to avoid overlapping with it, but I find it useful when refactoring.

**Comment by timsofteng** [comment]
> Assuming you've added it to your list of sources and it's shown as an active source when you run `:NullLsInfo`, it should generate diagnostics when you open or save files. You can populate the quickfix list with diagnostics for all files with errors using `:lua vim.diagnostic.setqflist()` or use a plugin like trouble.nvim.
> 
> Note that the behavior of the built-in is a little weird, since it assumes that the user is also running `typescript-language-server` and attempts to avoid overlapping with it, but I find it useful when refactoring.

Yes, I did exactly what you described.
But unfortunately diagnostic doesn't appear for closed files...

**Comment by timsofteng** [comment]
https://user-images.githubusercontent.com/51912173/150868118-071ea7d9-5f49-4e69-a1d9-446365095007.mp4

Here is brief screencast

**Comment by jose-elias-alvarez** [comment]
Could you open a separate issue, ideally with a minimal reproduction? I can't tell from the screencast, but unlike most null-ls sources (which update on every change) this one only runs when you first open or save a file.

**Comment by timsofteng** [comment]
> Could you open a separate issue, ideally with a minimal reproduction? I can't tell from the screencast, but unlike most null-ls sources (which update on every change) this one only runs when you first open or save a file.

I can but I'm not sure that I can describe there anything else except what I've already described here...

**Comment by jose-elias-alvarez** [comment]
Having the logs and being able to reproduce things on my end would help me see if this is a config issue or an issue with the plugin. I really can't tell 100% what's going on in the video.

**Comment by jose-elias-alvarez** [comment]
I think the underlying issue is "solved" in that we have a source that does what you want. If you're having issues with that source, please open another issue and provide the requested information so I can figure out what's going on.

**Comment by timsofteng** [comment]
Still doesn't work.
I'll open the issue.

**Comment by timsofteng** [comment]
@jose-elias-alvarez How can I reproduce anything with minial config?
It even doesn't contain lsp-config...
NulllsInfo doesn't show anything...
I can reproduce it with my personal config but can't with minimal.

**Comment by jose-elias-alvarez** [comment]
@timsofteng You can add nvim-lspconfig to the minimal config if it's necessary to reproduce the issue.
