### ISSUE TITLE
Diagnostics-On-Command mode

### ISSUE THREAD

**Issue by IndianBoy42** [jose-elias-alvarez/null-ls.nvim#660]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Currently we have `methods.internal.DIAGNOSTIC` which will run whenever there is a change, and `methods.internal.DIAGNOSTIC_ON_SAVE` which will run whenever we save the file. If there is something that gives diagnostics but takes too long to run, such that both of the former frequencies would be too high, then the ideal workflow is to be able to refresh the diagnostics only when a certain command is run or a function is called.

I think this could make null-ls applicable to a wider range of tools (like heavier static analyzers), as well support integrations like running a test suite and seeing the failing/succeeding tests through vim.diagnostic.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

If this doesn't require a big refactor of how the diagnostics are 'triggered' then I could try to implement it myself. Would it just be about not triggering on the normal events and adding a API function/command to allow them to trigger it manually?

**Comment by jose-elias-alvarez** [comment]
This sounds like a good idea. The simplest way I can think of would be to define [a new method](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/methods.lua#L19), then create a command to send a synthetic notification to the client to run sources for that method only (kind of like what we do [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/client.lua#L201)). This would also let users override the method for existing built-in sources so that they only run on demand.

**Comment by IndianBoy42** [comment]
Is it necessary for the `method` field of a source to be one of the elements of that array? or is the existence of that array just for reference/convenience? ie, if I configure a source and set its method to `"NULL_LS_CUSTOM_METHOD"` would it cause an error or just mean that the source wouldn't be run on the usual events?

**Comment by IndianBoy42** [comment]
I'll work on it soon. 

I was wondering because i wouldn't necessarily want to run all DIAGNOSTICS_ON_COMMAND sources at once. So the notification would need some way to tell null-ls which source to run, and I was just thinking what's the best way to do that. I don't fully understand how LSP notifications work so I'll have to dig into that

**Comment by jose-elias-alvarez** [comment]
The notifications are pretty arbitrary–as long as we send a method and URI to null-ls, it'll attempt to run diagnostic sources matching that method. Running individual sources will be more difficult, since we don't have a good way of doing this right now. I'd prefer to start with a new method for now and improve it from there (I also plan on improving the API in general in the future to make it easier to run things on demand).

**Comment by jose-elias-alvarez** [comment]
I've thought a bit more about this and am not sure that adding a new method is the right approach. I think a better approach would be to improve the source API and allow running sources on demand, which will require a larger rewrite, so I'm going to close this.
