### ISSUE TITLE
Provide function that exposes formatting without hooking into LSP

### ISSUE THREAD

**Issue by mjlbach** [jose-elias-alvarez/null-ls.nvim#697]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I get a *ton* of questions about how to disable formatting for language servers in favor of only using null-ls. The current solution is quite hacky (see: https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Avoiding-LSP-formatting-conflicts) as it effectively just tells neovim to ignore formatting requests in buf_request_all.

I'm not sure why this functionality cannot just be directly exposed, there is rarely an instance when a user would want to format with both null-ls and a language server (which is what buf request all effectively does). Then users can map a key to call the `null-ls` formatting directly. I don't see the value in shimming this into the protocol.

### Help

No

**Comment by jose-elias-alvarez** [comment]
The initial logic behind hooking into LSP formatting was to allow users to have a "unified" setup that lets them, say, use the same keybindings and commands for LSP formatting and null-ls formatting without having to worry about which one is currently active. I definitely agree that the majority of users only want to use one or the other, and I think providing separate command(s) + an API would solve a lot of headaches (though it might be a bit painful in terms of breaking user configs). I'll start working on a PR soon.

This is tangentially related, but I've been thinking about how to "de-LSP" all of null-ls, since I don't think the current approach is fundamentally sustainable. Making diagnostics independent would be straightforward and (mostly) seamless from the user perspective, but code actions and hover would have to go. I do think there may be merit in "centralizing" features like this and making it easier for plugins hook into them, VS Code-style, but is there any point in opening up an issue upstream to gauge interest?

**Comment by mjlbach** [comment]
> The initial logic behind hooking into LSP formatting was to allow users to have a "unified" setup that lets them, say, use the same keybindings and commands for LSP formatting and null-ls formatting without having to worry about which one is currently active. 

Yeah, I totally understand that. I think it would also be pretty easy to write a generic chain formatting command that sequentially checks if a source is available and calls it, so if you the require('null-ls').format == false -> call buf_request for the language servers.

> Making diagnostics independent would be straightforward and (mostly) seamless from the user perspective, but code actions and hover would have to go.

> I do think there may be merit in "centralizing" features like this and making it easier for plugins hook into them, VS Code-style, but is there any point in opening up an issue upstream to gauge interest?

As you know that was the motivation behind vim.diagnostic. We could extend that to formatting as well, as formatexpr is somewhat limited. I'm not sure code actions or hover should be their own functionality, as it's really coupled to LSP.

**Comment by jose-elias-alvarez** [comment]
> I'm not sure code actions or hover should be their own functionality, as it's really coupled to LSP.

This is just a single data point, but VS Code has a really nice API for extensions to act as providers for these and other features in an LSP-agnostic way. Either way, I think that discussion is more appropriate elsewhere, and I think the chaining approach is a great idea.

**Comment by jose-elias-alvarez** [comment]
I mentioned this in closing #703, the goal of which was to implement the requested feature, but for the record:

> The goal of this PR was to reduce conflicts between null-ls formatting and actual LSP formatting. I think `vim.lsp.buf.format` is a much nicer solution to that problem, so I'm going to close this PR.

Now, choosing / filtering out servers for formatting is simple, so I think this feature should no longer be necessary.
