### ISSUE TITLE
[DOCS] Unclear setup instructions in BUILTINS.md

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/null-ls.nvim#72]
Hey, in the docs for builtins, for every source the doc states that config is set up like so 

- Filetypes: `{ "asm" }`
- Command: `asmfmt`
- Arguments: `{}`

While configuring mine I assumed the param names would be `filetypes`, `command`, and `arguments`. While this is true for `filetypes`, and `command`, arguments actually take `args` param instead of `arguments`. Lost a few hours trying to figure it out a few days ago. 

More to the point, I doesn't state anywhere in `BUILTINS.md` that you should use `args` and not `arguments`.

I also found that in #35, there was the same problem. I assume I'm not the only person that is going to make that mistake. 

What do you think about the examples being written in the following format: 

```lua 
{
    command = 'prettier',
    filetypes = { 'css', 'html' },
    args = { '--no-semi', '--tab-width=4' }
}
```

That way people can just copy-paste and not have to figure out parameter names.

What do you think? 

I'd be happy to open a PR.

**Comment by jose-elias-alvarez** [comment]
I agree that using the term "arguments" is confusing, since the other two line up with the names of the keys but `args` does not. The reason (if I remember my own logic) that I avoided a code block containing the defaults was because I didn't want users to copy-paste the whole block Instead, I wanted to show a minimal example of what they needed to get the source working and also display the default configuration in case they needed to change it.

A code block is one option, but in my experience, if you give users a code block, they'll copy-paste the whole thing, and part of the reason I wanted to make null-ls was to reduce the amount of boilerplate users needed in their configs, so I wonder if we can think of anything else. A couple of other options I can think of: 

1. Change the format to how it would look in Lua, so that

> - Arguments: `{ "$FILENAME" }`

Turns into:

> - `args = { "$FILENAME" }`

2. Simply change `arguments` into `args` when registering sources (the laziest option)

I'm also open to any other ideas and am not 100% opposed to a code block if you think that's the best option.

**Comment by vuki656** [comment]
I see what you are saying and it does make sense. I like the first option. 

What do you think about the following format:

--- 
#### [isort](https://github.com/PyCQA/isort)

**About**

isort is a Python utility / library to sort imports alphabetically, and automatically separated into sections and by type.

**Usage**

```lua
local sources = { null_ls.builtins.formatting.isort }
```

**Defaults**

- `filetypes = { "python" }`
- `command = isort`
- `args = { "--stdout", "--profile", "black", "-" }`

---

If not, Ill just convert all the defaults to `args = { "test" }` format as that will fix the confusion.

**Comment by jose-elias-alvarez** [comment]
I think that's ideal – we avoid the copy-paste issue while still clearly stating the proper key to use.
