### ISSUE TITLE
Update diagnostics in real time for golangci_lint

### ISSUE THREAD

**Issue by taraslis453** [jose-elias-alvarez/null-ls.nvim#765]
Hello I'm using golangci_lint for diagnostics but it only updates when I save a file. Can I configure this server for updating in real time?

**Comment by jose-elias-alvarez** [comment]
Nope, this won't work because the linter needs to run on the full project in order to work properly, so updating on change doesn't work (we need to wait until the file is saved to run the linter again, or else the results won't be updated). I briefly mentioned this in [the documentation](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#diagnostics-on-save) but will think about how to make this clearer, since I imagine it's a common question.
