### ISSUE TITLE
Undoing changes sometimes duplicates lines after formatting, effectively breaking undo history.

### ISSUE THREAD

**Issue by jludwiggreenaction** [jose-elias-alvarez/null-ls.nvim#78]
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0-dev

### Steps to reproduce

I unfortunately have not yet been able to consistently reproduce this bug, but it happens fairly often.

It seems to happen when I'm formatting code with lots of braces/parenthesis, writing the file (this may not matter), and then undoing. 

Often, a single additional line is added on undo, right below the area that was formatted.

I have seen this issue with both `eslint_d` and `prettier`, so it does not seem related to any formatter in particular.

### Expected behavior

Undoing after formatting does not add an extra line.

### Actual behavior

Undoing after formatting sometimes adds an additional line and "corrupts" undo history. 

This additional line often contains text e.g. `)};`, which tends to break code. I believe it is a copy of the last line that was formatted in the file.

### Debug log

none

### Help

No

**Comment by jose-elias-alvarez** [comment]
Surprised to hear about this since I use the same formatters heavily and I've never seen anything like this. Are you using an autocommand to format on save, or do you trigger it manually? 

Under the hood, null-ls uses (almost) the same mechanism as actual LSP formatting, so this could also be a Neovim bug. Could you try setting `save_after_format = false` in your null-ls config and see if that makes a difference? If not, I think it's potentially a Neovim issue, since other than a small async formatting optimization we aren't doing anything else that could affect undos.

Could you also see if this happens with an actual LSP formatter (e.g. the `tsserver` formatter, which is terrible, but I'd like to see if it affects it, too), and could you give me an example of the code that seems to be more likely to trigger the issue?

**Comment by nghialm269** [comment]
I got similar issue in Python (using `black`), if after formatting the line count change, then the new lines got duplicated.
for example, format from: 
```python
test("123", "456", "789",)
```
to:
```python
test(
  "123",
  "456",
  "789",
)
```
result after formatting (something like this iirc):
```python
test(
  "123",
  "456",
  "789",
)
  "123",
  "456",
  "789",
)
```
the result is  corrected after I press `u` (undo), so maybe null-ls applied the changes twice?

**I was using the old way of setting up null-ls (before lspconfig), the issue went away after I migrated to the new setting using lspconfig.**

**Comment by jose-elias-alvarez** [comment]
@nghialm269 To make sure I understand, you are not *currently* seeing this issue on the latest version of null-ls and using the `lspconfig` config method, right? That PR included some changes that made formatting behave more like an actual language server, so it's possible that that's what fixed it.

**Comment by nghialm269** [comment]
@jose-elias-alvarez yes, I'm not having the issue anymore.

I was always using the latest version, it's just that I didn't use the `lspconfig` config method, the issue's gone after I switched to the `lspconfig` config method.

So maybe OP is using the old config method like I did when I had the issue.

**Comment by jose-elias-alvarez** [comment]
Thanks for confirming – glad to know it's working for you now. 

I definitely recommend updating and using the latest config method (if you're not already) and seeing if that makes a difference, @jludwiggreenaction.

**Comment by jludwiggreenaction** [comment]
@jose-elias-alvarez thanks for the info. I am already using the latest config method. Right now I'm testing to see if the same issue happens using efm.

**Comment by jludwiggreenaction** [comment]
So I have tried using EFM for a week and have not encountered any issues with formatting. So I'm pretty sure the issue is somehow with `null-ls`, but I still don't know how to reliably reproduce it.

**Comment by jose-elias-alvarez** [comment]
This is a guess, but is it at all possible that you're running multiple formatters on the same filetype, e.g. via an integration like [nvim-lsp-ts-utils](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils)? I ask because I saw behavior similar to what you describe while working on adding support for sequential formatting. 

If you don't mind posting your config and debug logs when you run a formatter, that would be a big help. Otherwise, I still haven't seen this behavior on my end, so there's not much I can do without reproduction.

**Comment by jludwiggreenaction** [comment]
Maybe that is the problem. I am using your `nvim-lsp-ts-utils` but I thought disabling the `eslint` integration would be enough. Below is what I have been using for `null-ls` formatting/diagnostics with `eslint_d`.
```lua  
local null_ls = require("null-ls")
null_ls.config({
  save_after_format = false,
  sources = {
    null_ls.builtins.formatting.eslint_d.with({
      filetypes = { "typescript", "javascript" },
    }),
  },
})

require("lspconfig")["null-ls"].setup({
  on_attach = function(client, bufnr)
    vim.api.nvim_buf_set_keymap(
      bufnr,
      "n",
      "<leader>z",
      "<cmd>lua vim.lsp.buf.formatting()<CR>",
      { noremap = true, silent = true }
    )
  end,
})

require("lspconfig").tsserver.setup({
  on_attach = function(client, bufnr)
    client.resolved_capabilities.document_formatting = false

    local ts_utils = require("nvim-lsp-ts-utils")

    ts_utils.setup({
      debug = false,
      disable_commands = false,
      enable_import_on_completion = false,

      -- import all
      import_all_timeout = 5000, -- ms
      import_all_priorities = {
        buffers = 4, -- loaded buffer names
        buffer_content = 3, -- loaded buffer content
        local_files = 2, -- git files or files with relative path markers
        same_file = 1, -- add to existing import statement
      },
      import_all_scan_buffers = 100,
      import_all_select_source = false,

      -- eslint
      eslint_enable_code_actions = false,
      eslint_enable_disable_comments = false,
      eslint_bin = "eslint_d",
      eslint_config_fallback = nil,
      eslint_enable_diagnostics = false,

      -- update imports on file move
      update_imports_on_move = false,
      require_confirmation_on_move = false,
      watch_dir = nil,
    })

    -- required to fix code action ranges
    ts_utils.setup_client(client)

    vim.api.nvim_buf_set_keymap(bufnr, "n", "tor", ":TSLspOrganize<CR>", { silent = true })
    vim.api.nvim_buf_set_keymap(bufnr, "n", "tqf", ":TSLspFixCurrent<CR>", { silent = true })
    vim.api.nvim_buf_set_keymap(bufnr, "n", "trn", ":TSLspRenameFile<CR>", { silent = true })
    vim.api.nvim_buf_set_keymap(bufnr, "n", "tia", ":TSLspImportAll<CR>", { silent = true })
  end,
  flags = {
    debounce_text_changes = 150,
  },
})
```

**Comment by jose-elias-alvarez** [comment]
Unfortunately (at least in this case) it looks like everything is working correctly, and double formatting is not happening, so that's not the reason. (The error is related to debugging and happens when `:messages` is left open too long.)

My final guess for now is that this could have to do with the timing with which we get the buffer's content before piping it to the formatter (another issue that came up while working on the feature). In that case, [the feature branch](https://github.com/jose-elias-alvarez/null-ls.nvim/tree/sequential-formatting) might help. I don't know how long it takes to trigger the error in question, but if you could try out the branch whenever you get a chance and let me know if it makes a difference, I'd appreciate it!

**Comment by jludwiggreenaction** [comment]
I'll give it a try, thanks for the support

**Comment by jludwiggreenaction** [comment]
Sorry for the delay.

I couldn't reproduce the issue after using the latest master for a bit and it seems the issue is resolved. Thanks for the help.
