### ISSUE TITLE
Code actions too slow

### ISSUE THREAD

**Issue by aridgupta** [jose-elias-alvarez/null-ls.nvim#8]
I don't know why but code actions are too slow. I have keybinding set to `ga` to bring up the available code actions, It takes around 2-3 seconds to bring up the list of code actions available. How do I reduce this?

**Comment by jose-elias-alvarez** [comment]
You're talking about ESLint code actions, right? I see from your config that you're using `eslint_d`. Getting and parsing output from `eslint_d` is nearly instantaneous on a medium-sized file (less than 0 ms on my end), so I don't think that's the cause.  

I remember you mentioned that you had recently moved to Neovim 0.5. If you haven't used `typescript-language-server` before, it might be slower than you expect, since everything has to pass through through two layers: `tsserver`, which is the actual language server, and `typescript-language-server`, which makes `tsserver` output LSP-compliant. 

If you comment out `null_ls.setup {}` in your config, does getting code actions feel significantly faster?

**Comment by aridgupta** [comment]
I am on `develop` branch of `nvim-lsp-ts-utils` and when I comment out `null_ls.setup {}` it's significantly faster.

**Comment by aridgupta** [comment]
I switched to `main` branch of `nvim-lsp-ts-utils` and commented out `null_ls.setup {}`. Code actions are fast but  formatting is broken.

**Comment by jose-elias-alvarez** [comment]
Right, if you comment out `null_ls.setup {}`, it will stop all of the integrations from working, including formatting. I suggested it as a way to check if null-ls was causing the issue.

Let me verify a couple of things from your nvim-lsp-ts-utils config.

1. Is `eslint_bin` set to `eslint_d`?
2. When you set `debug = true` in your nvim-lsp-ts-utils settings, does `:messages` show the message `using system executable eslint_d`, followed by `enabling null-ls eslint code actions integration`? 

If both of those are true, I'm afraid there's not much I can do to help, since code actions are nearly instantaneous on my end and there's no step in the process that should be causing any slowdown.

**Comment by aridgupta** [comment]
Something is wrong with my repo. Everything is working on other projects.

Since formatting is moved to `null-ls`, files that are in root directory of the project are not getting formatted.

**Comment by jose-elias-alvarez** [comment]
If the issue is restricted to a single repository, there's not much I can do to debug. Please investigate your project's configuration and open an issue on nvim-lsp-ts-utils if you're able to put together a minimal reproduction, both for Neovim and TypeScript.
