### ISSUE TITLE
`:checkhealth` is returning incorrect executable information when using `prefer_local`

### ISSUE THREAD

**Issue by ebcrowder** [jose-elias-alvarez/null-ls.nvim#912]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.8.0-dev

### Operating System

Linux

### Minimal config

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
	temp_dir = vim.loop.os_getenv("TEMP")
else
	temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
	local null_ls = require("null-ls")
	-- add only what you need to reproduce your issue
	null_ls.setup({
		sources = {
			null_ls.builtins.diagnostics.eslint.with({
				prefer_local = "node_modules/.bin",
			}),
			null_ls.builtins.formatting.prettier.with({
				prefer_local = "node_modules/.bin",
			}),
		},
		debug = true,
	})
end

local function load_plugins()
	-- only add other plugins if they are necessary to reproduce the issue
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"jose-elias-alvarez/null-ls.nvim",
				requires = { "nvim-lua/plenary.nvim" },
				config = null_ls_config,
			},
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	})
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
else
	load_plugins()
	require("packer").sync()
end
```

### Steps to reproduce

- Open `nvim` within a JavaScript/TypeScript project. The underlying `null-ls` configuration should specify `prefer_local` for both `eslint `and `prettier`.
- Ensure that `prettier` and `eslint` are included in the project's dependencies (`node_modules`)
- Run `:checkhealth` and note that the health test shows that `eslint` and `prettier` are not executable
- Examine files within the project and note that `eslint` and `prettier` are in fact executable as lint diagnostics exist (via `eslint`) and formatting functionality (via `prettier`) works correctly.

### Expected behavior

`:checkhealth` should show that `eslint` and `prettier` are executable.

### Actual behavior

`:checkhealth` shows that `eslint` and `prettier` are not executable.

### Debug log

N/A

### Help

Yes

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment]
This is a limitation of the health check. Basically, the idea here was that checking dynamic commands is unreliable outside of actual file buffers (and could potentially have side effects) so we just check [the raw command](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/dfdd5fab3c53c30f83c78ea351b9a8f65715a5b7/lua/null-ls/builtins/formatting/eslint.lua#L27). In this case, it means that the health check is effectively checking if there's a global `eslint` executable. 

We should for sure document this limitation somewhere and improve the messaging in the health check, as it's misleading (we have [a message](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/dfdd5fab3c53c30f83c78ea351b9a8f65715a5b7/lua/null-ls/health.lua#L8) that should cover this case but currently does not). 

It would be theoretically possible to check if a command was executable in the context of the last buffer that was open before the health check, but that would require us to somehow store this information *before* the health check window loads, since the report function runs once the window is open. I'm not necessarily opposed to it, but it's quite a lot of complexity to add.

**Comment by jose-elias-alvarez** [comment]
#1077 adds handling for `prefer_local` but leaves it at that. I added a note to the FAQ clarifying that health check results are for informational purposes and don't actually correlate with null-ls operation, since ultimately deciding whether a given command is executable has too many edge cases and will never be truly accurate.
