### ISSUE TITLE
Code Action fo rformatting

### ISSUE THREAD

**Issue by jalberto** [jose-elias-alvarez/null-ls.nvim#97]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I find formatting on save a bit odd, as I usually close the buffer when saving, so I suddenly have more changes than expected.

What about a feature that runs the formatting and show code actions where there are changes? So changes can be reviewed and applied one by one.

### Help

No

**Comment by jose-elias-alvarez** [comment]
I may be misunderstanding, but there's no need to format on save if that's not the behavior you want. You can run formatting on demand with `:lua vim.lsp.buf.formatting()`, which you can wrap with a Vim command / binding.

The code action idea is interesting but would be tricky to implement, since it would require us to identify and track exactly which parts of the file would be changed by formatting. If the goal is to format only part of a file, I think that's already accomplished by range formatting (see `:help vim.lsp.buf.range_formatting()`), which null-ls supports (though it's only implemented for a couple of formatters so far and not supported by every CLI formatter).

**Comment by jalberto** [comment]
That is what I do, run on demand, still, is a blind shot, but I understand
the complexity of knowing which lines have change.
I guess that the reason other formatting-plugins use a tmp file befor
eapplying the changes.

**Comment by jose-elias-alvarez** [comment]
Right. At the same time, I think it's worth remembering that null-ls isn't really a formatting plugin; rather, the goal is to emulate LSP functionality as closely as possible, and anything that goes too far beyond it probably belongs in another plugin (or in a custom LSP handler).

**Comment by jose-elias-alvarez** [comment]
I'm not planning on working on this myself and (if implemented) don't think it belongs in the core plugin, so I'm going to close this.
