### ISSUE TITLE
pylint: please display human-readable error code by default

### ISSUE THREAD

**Issue by bukzor** [jose-elias-alvarez/null-ls.nvim#999]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Background

The pylint tool has two names for each error code, where `W0621` and `redefined-outer-name` are treated as synonymous. The numeric names are older, while the human-readable names are newer and more useful. Best practice is to use the human-readable name when adding one-line exceptions to pylint rules (i.e. write `pylint: disable=redefined-outer-name` rather than `pylint: disable=W0621`).

### Feature description

Currently under `null-ls` it's harder than necessary to do this, because the numeric code (but not the human-readable code) is included in messaging by default.

I'm willing to configure a non-default here. I did have a look at the docs and add the code. While `symbol` is the "human readable error code" that I want, and it is captured in the null-ls-pylint handler, I didn't find any way to put it into the `diagnostics_format`.

That said, every user of pylint will have the same desire, so this should actually be default behavior.

This little patch forced null-ls into my desired behavior, but I doubt that it's acceptable for submission:

```lua
--- a/lua/null-ls/builtins/diagnostics/pylint.lua
+++ b/lua/null-ls/builtins/diagnostics/pylint.lua
@@ -23,10 +23,9 @@ return h.make_builtin({
             attributes = {
                 row = "line",
                 col = "column",
-                code = "message-id",
+                code = "symbol",
                 severity = "type",
                 message = "message",
-                symbol = "symbol",
                 source = "pylint",
             },
             severities = {
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

If you will please advise on exactly how you want to handle this problem, I can submit a patch with all tests passing.

**Comment by bukzor** [comment]
For anyone else happening upon this issue before it's closed, here's a workaround:

```
null_ls.setup({
  sources = {
    --null_ls.builtins.formatting.fixjson,
    --null_ls.builtins.completion.spell,
    null_ls.builtins.diagnostics.pylint.with({
      diagnostics_postprocess = function(diagnostic)
        diagnostic.code = diagnostic.symbol
      end,
    }),
    null_ls.builtins.formatting.isort,
    null_ls.builtins.formatting.black,
  },
})
```

I finally figured it out after sleuthing through the comments of #622 and #625.

**Comment by jose-elias-alvarez** [comment]
Could you link me to some sort of documentation / guidelines on the usage of the 2 different names? This is one of our older built-ins, and the issue hasn't come up before. 

For reference: [nvim-lint](https://github.com/mfussenegger/nvim-lint/blob/ac5f1b02d80a9ab6255263d14f158f0696f47bf1/lua/lint/linters/pylint.lua#L37) also uses `message-id`. Interestingly, it looks like ALE [allows users to configure which one to use](https://github.com/dense-analysis/ale/blob/7d8fb2ba1716a744446b811fc278ecf30d4eb771/ale_linters/python/pylint.vim#L79) via a buffer-local variable, but if I'm understanding the code correctly, it defaults to the human-readable name.

The VS Code extension might be a good example, too. It looks like messages are formatted using both the numeric code and the human-readable name:

<img width="370" alt="Screen Shot 2022-08-09 at 4 02 42 PM" src="https://user-images.githubusercontent.com/54108223/183750325-8eb98e2c-3dae-4d07-b082-d3007cea451a.png">

I don't really have a strong opinion apart from leaning towards maintaining the status quo, since this would be a breaking change to one of our more popular sources and it hasn't been an issue until now. Your workaround is also perfectly acceptable - the whole purpose of `diagnostics_postprocess` is to handle cases like this.

**Comment by bukzor** [comment]
Sure, here are some references.

This is the pylint doc explaining how to suppress messages. You can see they've used the long names everywhere and the numeric names zero times: https://pylint.pycqa.org/en/latest/user_guide/messages/message_control.html

There's even a checker to remind people to use the human-readable rather than numeric message names:
https://pylint.pycqa.org/en/latest/user_guide/messages/information/use-symbolic-message-instead.html?highlight=symbolic

The relevant changelog says: (from https://pylint.pycqa.org/en/latest/whatsnew/2/2.0/summary.html)

> New use-symbolic-message-instead message when a message is activated or deactivated by id instead of symbol. The use of symbol is more explicit and easier to remind.

The google python styleguide shows use of "symbolic" names for pylint: 
https://google.github.io/styleguide/pyguide.html#214-decision


The EdX styleguide explicitly recommends the "full name" as well:  ( from https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#pylint-guidelines-and-practices)

> The pragma starts with a # two spaces after the end of the line. We prefer that you use the full name of the error (pylint: disable=unused- argument as opposed to pylint: disable=W0613), so that it is more clear what you are disabling in the line.

**Comment by bukzor** [comment]
> Interestingly, it looks like ALE [allows users to configure which one to use](https://github.com/dense-analysis/ale/blob/7d8fb2ba1716a744446b811fc278ecf30d4eb771/ale_linters/python/pylint.vim#L79) via a buffer-local variable, but if I'm understanding the code correctly, it defaults to the human-readable name.

You are understanding the code incorrectly, with all due respect :) These are the relevant bits:

```vim
call ale#Set('python_pylint_use_msg_id', 0)
...
    " Matches patterns like the following:
    "
    " test.py:4:4: W0101 (unreachable) Unreachable code
    let l:pattern = '\v^[a-zA-Z]?:?[^:]+:(\d+):(\d+): ([[:alnum:]]+) \(([^(]*)\) (.*)$'

    for l:match in ale#util#GetMatches(a:lines, l:pattern)
      ...
      if ale#Var(a:buffer, 'python_pylint_use_msg_id') is# 1
          let l:code_out = l:code
      else
          let l:code_out = l:match[4]
      endif
```

By default, only the `else` path will be used, which sets "code" from the fourth match of the regex, the warning name.

Originally w0rm (the ALE maintainer) set things to unconditionally use the long name (as I'm asking null-ls to do), but someone made a drive-by request for a flag:  https://github.com/dense-analysis/ale/issues/852#issuecomment-344669312

Because that person was never heard from again (apart from their complaint), and because I've found zero references to `g:ale_python_pylint_use_msg_id` on the entire internet (apart from its bug, implementation and doc), I am confidently asserting that it was nothing more than a ["spacebar heating" feature request](https://xkcd.com/1172/). But I'll understand if you decide to skip the hassle :)

I'll bet you a banana though, if you post my "workaround" above in your documentation, you'll find it's the most common configuration of ls-null pylint in a year's time. I'd even bet two bananas.

**Comment by jose-elias-alvarez** [comment]
Thanks for putting this together - your references seem pretty definitive on the issue, so let's go ahead and make the change. 

I'm happy to review a PR, though since it's technically a breaking change for anybody relying on the numeric code, it'd be nice if we could still keep it on a separate field + provide a copy-paste way to revert to the old behavior (basically the inverse of the workaround you posted).

**Comment by bukzor** [comment]
I'll start on the change tomorrow. It will include an addition to docs describing an inverse to my workaround.
